### ISSUE TITLE
Essentia alternative for Windows

### ISSUE THREAD

**Issue by kjellvb** [oguzhan-yilmaz/pyCrossfade#1]
Hello, thank you for this project, it works nice on Linux. However I would now like to run it on Windows, but Essentia with python bindings is not available for Windows, do you know a way around this, or an alternative that can be used instead of Essentia?
Thanks :-)

**Comment by oguzhan-prplbx** [comment]
Hey, I couldn't get Essentia to work on Windows too. I would suggest that you setup [WSL ](https://docs.microsoft.com/en-us/windows/wsl/install-win10)if you have Windows 10. WSL is a linux kernel that works within Windows 10, and is fairly simple to use.
