### ISSUE TITLE
No stereo output support?

### ISSUE THREAD

**Issue by metehanpala** [oguzhan-yilmaz/pyCrossfade#3]
I've been experimenting with pyCrossfade, and one thing that struck me was the lack of a "Mono" or "Stereo" output option. It just exports audio as Mono. I dug a little more into the source code but couldn't locate the precise cause of the problem; I believe it's something to do with an external library you use. Is it possible to export the audio as Stereo?

**Comment by oguzhan-yilmaz** [comment]
Hey, I was only able to make it work with mono audio. I believe Essentia library has a stereo audio reader but it would require doing what pyCrossfade does on multiple sound channels.
