### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by markhanslip** [oguzhan-yilmaz/pyCrossfade#4]
Any ideas on this please? I have all dependencies and cython was installed before madmom. 

Thanks,

Mark

**Comment by oguzhan-yilmaz** [comment]
Can you please provide more details such as logs, information on your system etc. I can't really tell what's the problem.
